# Site settings
title: Cabac - back to life
email: backtolife@cabac.org
description: "The Cameroonian Brotherhood Association of Chicago, was founded in 1997 in Chicago. In an act of consciousness of many plagues endured in Africa and a firm resolution not to stand by and do nothing. CABAC was incorporated in the State of Illinois in 2002 and granted the 501 c3 tax status in 2006"
baseurl: ""
url: "http://cabac.org"
twitter_username: cabacorg
#github_username:  gtemgoua

# Build settings
markdown: kramdown
permalink: pretty
